apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: grafana-admin-credentials
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: admin
      remoteRef:
        key: grafana_admin_credentials_secret
        property: admin
    - secretKey: password
      remoteRef:
        key: grafana_admin_credentials_secret
        property: password
