replicaCount: 3
rollingUpdate:
  maxUnavailable: 1
  maxSurge: 1
matchLabels:
  app: memos-app
securityContext:
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001
  runAsNonRoot: true
image:
  repository: 441336784821.dkr.ecr.eu-west-2.amazonaws.com/eks-memos-application
  tag: sha-5d70b5f
  digest: "sha256:a4a89ee303492bf54b7c442884fb537b83f7f80e1745f15eae504a003b685d67"
containerPort: 5230
dsn:
  secretName: memos-dsn
  secretKey: dsn
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 128Mi
##ingress.yml
hostname: memo.sehindemi.com
clusterIssuer: letsencrypt-https
## limit ranges
limitRange:
  default:
    cpu: 200m
    memory: 256Mi
  defaultRequest:
    cpu: 100m
    memory: 128Mi
  min:
    cpu: 50m
    memory: 64Mi
  max:
    cpu: 500m
    memory: 512Mi
