provider:
  name: aws
  aws:
    region: eu-west-2

sources:
  - ingress

policy: sync
txtOwnerId: eks-memos-application-external-dns
domainFilters:
  - memo.sehindemi.com

serviceAccount:
  name: external-dns