apiVersion: apps/v1
kind: Deployment
metadata:
  name: memos-app

spec:
  replicas: {{ .Values.replicaCount }}

  strategy:
    rollingUpdate:
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}

  selector:
    matchLabels:
      app: {{ .Values.matchLables.app }}

  template:
    metadata:
      labels:
        app: {{ .Values.matchLables.app }}

    spec:
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
        runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}

      containers:
        - name: memos
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.containerPort }}

          env:
            - name: MEMOS_PORT
              value: "{{ .Values.containerPort }}"

            - name: MEMOS_DRIVER
              value: "postgres"

            - name: MEMOS_DSN
              valueFrom:
                secretKeyRef:
                  name: {{  .Values.dsn.secretName }}
                  key: {{ .Values.dsn.secretKey }}

          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3


          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}

            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory}}