apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: memos-app
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.clusterIssuer }}
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - {{ .Values.hostname }}
      secretName: memos-tls

  rules:
    - host: {{ .Values.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: memos
                port:
                  number: {{ .Values.containerPort }}