apiVersion: v1
kind: Service
metadata:
  name: memos
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.containerPort }}
      targetPort: {{ .Values.containerPort }}

  selector:
    app: memos-app