apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-secret-store
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sehindemi-tech/EKS-Memos-Application.git
    targetRevision: main
    path: infra/kubernetes/manifests/cluster-secret-store
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true