apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: memos
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sehindemi-tech/EKS-Memos-Application.git
    targetRevision: main
    path: infra/kubernetes/my-chart/memo-app
  destination:
    server: https://kubernetes.default.svc
    namespace: memos-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true