apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: memos-dsn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sehindemi-tech/EKS-Memos-Application.git
    targetRevision: main
    path: infra/kubernetes/manifests/memos-app-dsn
  destination:
    server: https://kubernetes.default.svc
    namespace: memos
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true