apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 91.4.0
      helm:
        valueFiles:
          - $values/infra/kubernetes/values/prometheus-stack.yaml

    - repoURL: https://github.com/sehindemi-tech/EKS-Memos-Application.git
      targetRevision: main
      ref: values
      path: infra/kubernetes/values

    - repoURL: https://github.com/sehindemi-tech/EKS-Memos-Application.git
      targetRevision: main
      path: infra/kubernetes/infrastructure/monitoring/monitoring-external-secrets

    - repoURL: https://github.com/sehindemi-tech/EKS-Memos-Application.git
      targetRevision: main
      path: infra/kubernetes/infrastructure/monitoring/monitoring-ingress

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true