apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prometheus-basic-auth
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: monitoring-middleware-auth
    creationPolicy: Owner
  data:
    - secretKey: users
      remoteRef:
        key: prometheus_basic_auth_secret
        property: htpasswd
